version: '3'
services:
  mydb:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      mysql_USER: myuser
      mysql_PASSWORD: mypassword
      mysql_DB: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal_network

  myapp:
    container_name: app
    build:
      context: ./app
    ports:
      - "1000:1000"
    depends_on:
      - mydb
    environment:
      DB_HOST: mydb
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    networks:
      - internal_network

  mygateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "2000:2000"
    depends_on:
      - mydb
    environment:
      DB_HOST: mydb
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    networks:
      - internal_network

networks:
  internal_network:

volumes:
  mysql_data:
